package multitier.trans.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entity class representing the 'routes' table in the PostgreSQL database.
 * This class defines the structure for persistent Route data.
 */
@Entity
@Table(name = "routes")
public class Route {

    // Primary Key (ID) - automatically generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Route Details
    private String originCity;
    private String destinationCity;
    private int vehicleCapacity;

    // --- Constructors ---

    // Default constructor is required by JPA/Hibernate
    public Route() {
    }

    public Route(String originCity, String destinationCity, int vehicleCapacity) {
        this.originCity = originCity;
        this.destinationCity = destinationCity;
        this.vehicleCapacity = vehicleCapacity;
    }

    // --- Getters and Setters ---

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOriginCity() {
        return originCity;
    }

    public void setOriginCity(String originCity) {
        this.originCity = originCity;
    }

    public String getDestinationCity() {
        return destinationCity;
    }

    public void setDestinationCity(String destinationCity) {
        this.destinationCity = destinationCity;
    }

    public int getVehicleCapacity() {
        return vehicleCapacity;
    }

    public void setVehicleCapacity(int vehicleCapacity) {
        this.vehicleCapacity = vehicleCapacity;
    }
}
